version: "3.6"
services:
  api:
    build: .
    image: node-image-generator:1.0
    ports:
      - "127.0.0.1:6543:6543"
    volumes:
      - .:/usr/src/app
    container_name: image-generator-test
    command: "npm start"